/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package warehouse;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author magic
 */
public class AddingCompany extends javax.swing.JFrame {

    /**
     * Creates new form company
     */
    public AddingCompany() {
        initComponents();
        prestart();
    }
void prestart (){
try {
    Connection conn = ConnectDataBase.connect();
    PreparedStatement ps = conn.prepareStatement("select MAX(companyID) from company");
    ResultSet rs = ps.executeQuery();
    rs.next();
    txtCompanyID.setText("" + (Integer.parseInt(rs.getString(1))+1));
    txtCompanyID.setEditable(false);
}
catch (Exception ex){

}

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        lblCompanyID = new javax.swing.JLabel();
        lblCompanyName = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblCEOName = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblFax = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        txtCompanyID = new javax.swing.JTextField();
        txtCompanyName = new javax.swing.JTextField();
        txtLocation = new javax.swing.JTextField();
        txtCEOName = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        txtFax = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adding Company");

        lblCompanyID.setText("Company ID");

        lblCompanyName.setText("Company Name");

        lblLocation.setText("Location");

        lblCEOName.setText("CEO Name");

        lblPhoneNumber.setText("Phone Number");

        lblFax.setText("Fax");

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCompanyName)
                        .addComponent(lblCompanyID)
                        .addComponent(lblLocation)
                        .addComponent(lblPhoneNumber)
                        .addComponent(lblFax)
                        .addComponent(lblCEOName))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(MainPanelLayout.createSequentialGroup()
                                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCEOName)
                                    .addComponent(txtCompanyName, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtCompanyID)
                                    .addComponent(txtLocation, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblCompanyID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtCompanyID, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCompanyName)
                            .addComponent(txtCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLocation)
                            .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(lblCEOName))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txtCEOName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lblPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFax))
                .addGap(18, 18, 18)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(clearButton)
                    .addComponent(backButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
    if (txtCompanyID.getText().toString().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter company ID");
       return;
    }
    if (!Controller.validateIntegerNumber(txtCompanyID.getText().toString()))
    {
    JOptionPane.showMessageDialog(null, "Enter a valid company ID");
      return;
    }
    if (txtCompanyName.getText().toString().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter company Name");
       return;
    }
    if (!Controller.validateName(txtCompanyName.getText().toString()))
    {
    JOptionPane.showMessageDialog(null, "Enter a valid company Name");
      return;
    }
    if (txtLocation.getText().toString().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter company location");
       return;
    }
   if (txtCEOName.getText().toString().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter company CEO name");
       return;
    }
    if (!Controller.validateName(txtCEOName.getText().toString()))
    {
    JOptionPane.showMessageDialog(null, "Enter a valid company CEO name");
      return;
    }
        if (txtPhoneNumber.getText().toString().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter company phone number");
       return;
    }
    if (!Controller.validateIntegerNumber(txtPhoneNumber.getText().toString()))
    {
    JOptionPane.showMessageDialog(null, "Enter a valid company phone number");
      return;
    }
    if (txtFax.getText().toString().equals(""))
    {
        JOptionPane.showMessageDialog(null, "Enter company FAx");
       return;
    }
    if (!Controller.validateIntegerNumber(txtFax.getText().toString()))
    {
    JOptionPane.showMessageDialog(null, "Enter a valid company Fax");
      return;
    }
    try {
    Connection conn = ConnectDataBase.connect();
        PreparedStatement ps = conn.prepareStatement("insert into company (companyID , companyName , location , fax ,phoneNumber , CEOName) values (? , ? , ? , ? , ? , ?)");
        ps.setString(1, txtCompanyID.getText().toString());
       ps.setString(2, txtCompanyName.getText().toString());
       ps.setString(3, txtLocation.getText().toString());
       ps.setString(4, txtFax.getText().toString());
       ps.setString(5, txtPhoneNumber.getText().toString());
       ps.setString(6, txtCEOName.getText().toString());
       ps.execute();
       JOptionPane.showMessageDialog(null, "1 row Inserted");
    }
    catch (Exception ex){
    JOptionPane.showMessageDialog(null, ex.getMessage());
    }
    
    
    
    
    
    
    
    
    
    
    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
txtCompanyID.setText("");
txtCompanyName.setText("");
txtLocation.setText("");
txtPhoneNumber.setText("");
txtFax.setText("");
txtCEOName.setText("");
prestart();
       
    }//GEN-LAST:event_clearButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
    this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddingCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddingCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddingCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddingCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddingCompany().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton addButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel lblCEOName;
    private javax.swing.JLabel lblCompanyID;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JTextField txtCEOName;
    private javax.swing.JTextField txtCompanyID;
    private javax.swing.JTextField txtCompanyName;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
